// ============================================================================
// TERMS OF SERVICE CONTENT
// ============================================================================
// Comprehensive Terms of Service for Rakri AI Platform
// Covers both website usage and SaaS platform services
// Last Updated: January 2025
// ============================================================================

export const termsOfServiceContent = {
  lastUpdated: "January 17, 2025",
  effectiveDate: "January 17, 2025",

  sections: [
    {
      id: "introduction",
      title: "1. Introduction and Acceptance of Terms",
      content: [
        {
          type: "paragraph",
          text: "Welcome to Rakri AI. These Terms of Service ('Terms', 'Agreement') constitute a legally binding agreement between you ('you', 'your', 'Client', 'User') and Rakri AI ('we', 'us', 'our', 'Company') governing your access to and use of the Rakri AI website (rakriai.com) and AI-powered recruitment platform services (collectively, the 'Services')."
        },
        {
          type: "important",
          text: "BY ACCESSING OR USING OUR SERVICES, YOU AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE TO THESE TERMS, DO NOT USE OUR SERVICES."
        },
        {
          type: "paragraph",
          text: "These Terms apply to:"
        },
        {
          type: "list",
          items: [
            "Website Visitors: Individuals browsing rakriai.com",
            "Prospective Clients: Organizations requesting demos or information",
            "Platform Clients: Organizations with active subscription agreements",
            "Authorized Users: Employees and contractors of Client organizations who access the platform",
            "Candidates: Job applicants whose data is processed through the platform (subject to client privacy policies)"
          ]
        },
        {
          type: "paragraph",
          text: "Additional Terms: Enterprise clients will enter into a separate Master Services Agreement (MSA) and Data Processing Agreement (DPA) that supplement these Terms. In case of conflict, the MSA and DPA take precedence."
        }
      ]
    },
    {
      id: "definitions",
      title: "2. Definitions",
      content: [
        {
          type: "paragraph",
          text: "For purposes of these Terms:"
        },
        {
          type: "definition-list",
          items: [
            {
              term: "Platform",
              definition: "The Rakri AI software-as-a-service (SaaS) application for AI-powered candidate screening and recruitment automation"
            },
            {
              term: "Client",
              definition: "An organization (recruitment agency, employer, enterprise) that has subscribed to the Platform services"
            },
            {
              term: "Authorized User",
              definition: "An individual authorized by a Client to access and use the Platform (recruiters, hiring managers, administrators)"
            },
            {
              term: "Candidate",
              definition: "A job applicant whose resume/CV and application data is processed through the Platform"
            },
            {
              term: "Candidate Data",
              definition: "Personal data of Candidates including resumes, applications, scores, and related information"
            },
            {
              term: "Client Data",
              definition: "All data submitted, uploaded, or generated by Client through the Platform, including Candidate Data"
            },
            {
              term: "AI Services",
              definition: "Machine learning models and algorithms that analyze resumes, score candidates, and provide recommendations"
            },
            {
              term: "Client Infrastructure",
              definition: "Client-designated cloud environment (AWS, Azure, GCP) where the Platform and Client Data are hosted"
            }
          ]
        }
      ]
    },
    {
      id: "service-description",
      title: "3. Service Description",
      content: [
        {
          type: "subsection",
          title: "3.1 Core Services",
          text: "Rakri AI provides an AI-powered recruitment platform that includes:"
        },
        {
          type: "list",
          items: [
            "Resume Parsing: Automated extraction and analysis of candidate CVs and application materials",
            "AI Candidate Scoring: Machine learning-based evaluation and ranking of candidates against job requirements",
            "Explainable AI: Transparent reasoning and explanations for all scoring decisions",
            "Workflow Automation: Configurable screening workflows (Human-in-the-Loop or Fully Autonomous)",
            "Analytics Dashboard: Recruitment metrics, insights, and performance tracking",
            "Integration Services: Connections to LinkedIn, ATS systems, career sites, and other recruitment tools",
            "GDPR Compliance Tools: Audit logs, data deletion, consent management, and compliance reporting"
          ]
        },
        {
          type: "subsection",
          title: "3.2 Deployment Model",
          text: "The Platform operates on a client-hosted deployment model:"
        },
        {
          type: "list",
          items: [
            "Client Infrastructure: Platform is deployed on Client's designated cloud environment (AWS, Azure, GCP)",
            "Data Ownership: Client retains full ownership and control of all Client Data",
            "Data Location: Client specifies geographic region for data storage (e.g., EU, US)",
            "Isolation: Each Client's environment is logically isolated from other clients",
            "Security: Enterprise-grade encryption in transit (TLS 1.2+) and at rest (AES-256)"
          ]
        },
        {
          type: "subsection",
          title: "3.3 Service Levels",
          text: "We strive to maintain high service availability and performance:"
        },
        {
          type: "list",
          items: [
            "Availability Target: 99.5% uptime (excluding scheduled maintenance)",
            "Scheduled Maintenance: Announced at least 48 hours in advance, typically performed during off-peak hours",
            "Support Hours: Monday - Friday, 9:00 AM - 6:00 PM CET",
            "Response Times: Critical issues within 4 hours, non-critical within 24 hours (business days)",
            "Performance: Candidate scoring typically completed within 2-5 seconds per resume"
          ]
        },
        {
          type: "important",
          text: "Service Level Agreements (SLAs): Enterprise clients may negotiate specific SLA terms in their Master Services Agreement, including uptime guarantees, response times, and service credits for downtime."
        }
      ]
    },
    {
      id: "eligibility",
      title: "4. Eligibility and Account Registration",
      content: [
        {
          type: "subsection",
          title: "4.1 Eligibility Requirements",
          text: "To use our Services, you must:"
        },
        {
          type: "list",
          items: [
            "Be at least 18 years old (or the age of majority in your jurisdiction)",
            "Represent a legitimate business entity (for Platform services)",
            "Have legal authority to bind your organization to these Terms",
            "Comply with all applicable laws, including employment and data protection regulations",
            "Not be located in a country subject to US or EU sanctions or embargoes"
          ]
        },
        {
          type: "subsection",
          title: "4.2 Account Registration (Platform Clients)",
          text: "To access the Platform, Clients must:"
        },
        {
          type: "list",
          items: [
            "Complete the onboarding process and provide accurate business information",
            "Designate at least one Administrator with full account management rights",
            "Provide valid contact information (email, phone, business address)",
            "Accept these Terms, our Privacy Policy, and sign a Data Processing Agreement",
            "Complete payment setup and provide valid billing information"
          ]
        },
        {
          type: "subsection",
          title: "4.3 User Accounts and Security",
          text: "Authorized Users must:"
        },
        {
          type: "list",
          items: [
            "Create individual accounts with unique credentials (no shared accounts)",
            "Maintain confidentiality of login credentials",
            "Enable multi-factor authentication (MFA) when available",
            "Immediately notify Client Administrator and Rakri AI of any unauthorized access",
            "Accept responsibility for all activities under their account"
          ]
        },
        {
          type: "important",
          text: "Account Security: Clients are responsible for maintaining the security of Authorized User accounts. Rakri AI is not liable for losses resulting from unauthorized use of Client credentials."
        },
        {
          type: "subsection",
          title: "4.4 Prohibited Users",
          text: "You may not use our Services if you:"
        },
        {
          type: "list",
          items: [
            "Have been previously suspended or banned from our Services",
            "Are a competitor seeking to copy, reverse-engineer, or benchmark our Services",
            "Intend to use the Services for illegal, fraudulent, or discriminatory purposes",
            "Are subject to legal restrictions preventing use of AI or recruitment technologies"
          ]
        }
      ]
    },
    {
      id: "pricing-payment",
      title: "5. Pricing, Payment Terms, and Billing",
      content: [
        {
          type: "subsection",
          title: "5.1 Pricing Structure",
          text: "Rakri AI operates on a transparent, three-tier pricing model:"
        },
        {
          type: "pricing-table",
          items: [
            {
              tier: "Project Setup & Deployment (One-Time)",
              price: "€18,000 - €35,000",
              description: "Complete cloud environment setup, system integration, data migration, security configuration, team training, and initial AI model tuning. Price varies based on complexity, integrations, and customization requirements."
            },
            {
              tier: "AI Usage Charges (Pay-Per-Use)",
              price: "€2 - €4 per candidate scored",
              description: "Variable cost based on usage volume. Includes resume parsing, AI scoring, explainable reasoning generation, and all platform features. Transparent usage tracking via dashboard. Higher volumes may qualify for volume discounts."
            },
            {
              tier: "Annual Support & Updates (Optional)",
              price: "Starting at €1,500/year",
              description: "Security patches, GDPR compliance monitoring, technical support (CET business hours), performance optimization, and feature enhancements. Recommended for enterprise clients."
            }
          ]
        },
        {
          type: "subsection",
          title: "5.2 Payment Terms",
          text: "Payment terms and conditions:"
        },
        {
          type: "list",
          items: [
            "Project Setup: 50% due upon contract signing, 50% due upon deployment completion",
            "Usage Charges: Invoiced monthly in arrears based on actual usage (candidates scored)",
            "Annual Support: Invoiced annually in advance (prorated for mid-year starts)",
            "Currency: All prices in Euro (€) unless otherwise specified in MSA",
            "Payment Methods: Bank transfer, credit card, or other methods agreed in MSA",
            "Payment Due Date: Net 30 days from invoice date"
          ]
        },
        {
          type: "subsection",
          title: "5.3 Late Payments and Suspension",
          text: "Late payment consequences:"
        },
        {
          type: "list",
          items: [
            "Late Fee: 1.5% per month (or maximum allowed by law) on overdue amounts",
            "Suspension Notice: We will provide 10 days written notice before suspending Services",
            "Service Suspension: Access may be suspended for accounts more than 30 days overdue",
            "Data Access: During suspension, Clients retain read-only access to export Client Data",
            "Termination: Accounts overdue more than 60 days may be terminated (see Section 12)"
          ]
        },
        {
          type: "subsection",
          title: "5.4 Taxes",
          text: "Tax responsibilities:"
        },
        {
          type: "list",
          items: [
            "Prices are exclusive of all taxes, duties, and levies",
            "Client is responsible for all applicable sales, use, VAT, GST, and similar taxes",
            "EU VAT: Reverse charge mechanism applies for EU B2B transactions (provide valid VAT number)",
            "Withholding Tax: Client must pay gross amount; any withholding taxes are Client's responsibility",
            "Tax Documentation: Client must provide all required tax certificates and documentation"
          ]
        },
        {
          type: "subsection",
          title: "5.5 Price Changes",
          text: "We reserve the right to modify pricing:"
        },
        {
          type: "list",
          items: [
            "Usage Charges: May be adjusted annually with 90 days written notice",
            "Annual Support: May increase at renewal based on CPI or 5% (whichever is greater)",
            "Existing Contracts: Price changes do not affect active contract terms (grandfathered)",
            "Early Renewal: Clients may renew early to lock in current pricing for extended term"
          ]
        },
        {
          type: "important",
          text: "No Hidden Fees: All costs are transparently itemized in invoices. Usage dashboard provides real-time cost tracking to prevent billing surprises."
        }
      ]
    },
    {
      id: "acceptable-use",
      title: "6. Acceptable Use Policy",
      content: [
        {
          type: "paragraph",
          text: "You agree to use our Services responsibly and in compliance with all applicable laws. Prohibited uses include:"
        },
        {
          type: "subsection",
          title: "6.1 Illegal and Harmful Activities",
          text: "You may NOT use our Services to:"
        },
        {
          type: "list",
          items: [
            "Violate any laws, regulations, or rights of others (including employment, privacy, and anti-discrimination laws)",
            "Engage in discriminatory hiring practices based on protected characteristics (race, gender, age, disability, etc.)",
            "Process data of individuals without proper legal basis or consent",
            "Conduct fraudulent activities or misrepresent your identity or business",
            "Harass, threaten, or abuse others (including candidates and employees)",
            "Distribute malware, viruses, or harmful code",
            "Conduct security attacks, penetration testing, or vulnerability scanning without authorization"
          ]
        },
        {
          type: "subsection",
          title: "6.2 Platform Misuse",
          text: "You may NOT:"
        },
        {
          type: "list",
          items: [
            "Reverse engineer, decompile, or disassemble the Platform or AI models",
            "Access the Platform through automated means (bots, scrapers) except through authorized APIs",
            "Attempt to gain unauthorized access to systems, accounts, or data",
            "Interfere with or disrupt the integrity or performance of the Services",
            "Remove, obscure, or alter any proprietary notices (copyright, trademarks)",
            "Use the Services to develop competing products or services",
            "Share your account credentials or allow unauthorized third-party access",
            "Exceed reasonable usage limits or engage in abusive usage patterns (e.g., submitting thousands of duplicate resumes)"
          ]
        },
        {
          type: "subsection",
          title: "6.3 Data and Content Standards",
          text: "You may NOT submit or process:"
        },
        {
          type: "list",
          items: [
            "Illegal Content: Child exploitation material, terrorist content, illegal drug content",
            "Sensitive Data Without Proper Basis: Health data, biometric data, criminal records without explicit legal basis and candidate consent",
            "Discriminatory Content: Job requirements or screening criteria that unlawfully discriminate against protected groups",
            "Misleading Information: False or deceptive job postings or company information",
            "Spam or Unsolicited Communications: Bulk unsolicited candidate outreach",
            "Infringing Content: Material that violates intellectual property, privacy, or other rights"
          ]
        },
        {
          type: "subsection",
          title: "6.4 Employment Law Compliance",
          text: "Clients must:"
        },
        {
          type: "list",
          items: [
            "Comply with all applicable employment and labor laws in their jurisdiction",
            "Obtain necessary candidate consent for data processing and automated decision-making",
            "Ensure job requirements and screening criteria are non-discriminatory and job-related",
            "Provide candidates with required notices about AI-powered screening (GDPR Art. 22)",
            "Implement human oversight for final hiring decisions (or obtain candidate consent for fully automated decisions)",
            "Maintain audit trails and documentation for compliance investigations",
            "Respond to candidate rights requests (access, deletion, objection) in accordance with applicable law"
          ]
        },
        {
          type: "subsection",
          title: "6.5 Enforcement and Consequences",
          text: "Violation of this Acceptable Use Policy may result in:"
        },
        {
          type: "list",
          items: [
            "Warning and request to cease prohibited activity",
            "Temporary suspension of Services pending investigation",
            "Permanent termination of account and Services",
            "Deletion of violating content or data",
            "Legal action and cooperation with law enforcement",
            "No refund of fees paid for services terminated due to violations"
          ]
        },
        {
          type: "important",
          text: "Reporting Violations: If you become aware of any violations of this policy, please report them immediately to connect@rakriai.com. We investigate all reports and take appropriate action."
        }
      ]
    },
    {
      id: "data-protection",
      title: "7. Data Protection and Privacy",
      content: [
        {
          type: "paragraph",
          text: "Data protection is central to our Services. This section outlines data responsibilities under GDPR and other privacy laws."
        },
        {
          type: "subsection",
          title: "7.1 Data Processing Roles",
          text: "The data protection relationship works as follows:"
        },
        {
          type: "list",
          items: [
            "Client as Data Controller: For Candidate Data, Client is the data controller who determines purposes and means of processing",
            "Rakri AI as Data Processor: We process Candidate Data on behalf of and according to Client's instructions",
            "Rakri AI as Data Controller: For website contact form data and Client account data, we are the data controller",
            "Data Processing Agreement (DPA): All Clients must sign our standard DPA (compliant with GDPR Art. 28)"
          ]
        },
        {
          type: "subsection",
          title: "7.2 Client Responsibilities (as Data Controller)",
          text: "Clients must:"
        },
        {
          type: "list",
          items: [
            "Have a valid legal basis for processing Candidate Data (consent, contract, legitimate interest)",
            "Provide candidates with transparent privacy notices explaining AI-powered screening",
            "Obtain necessary consents for automated decision-making (GDPR Art. 22)",
            "Respond to candidate rights requests (access, deletion, objection, portability)",
            "Implement appropriate data retention policies and delete data when no longer needed",
            "Ensure data accuracy and allow candidates to correct inaccurate information",
            "Conduct Data Protection Impact Assessments (DPIA) where required",
            "Notify Rakri AI immediately of any data breaches involving Candidate Data"
          ]
        },
        {
          type: "subsection",
          title: "7.3 Rakri AI Responsibilities (as Data Processor)",
          text: "We commit to:"
        },
        {
          type: "list",
          items: [
            "Process Candidate Data only according to Client's documented instructions",
            "Implement appropriate technical and organizational security measures (see Section 8)",
            "Maintain confidentiality of Candidate Data (employee confidentiality agreements)",
            "Assist Client in responding to candidate rights requests",
            "Assist Client with DPIAs and consultations with supervisory authorities",
            "Delete or return Candidate Data upon contract termination (per Client instruction)",
            "Notify Client of data breaches within 24 hours of discovery",
            "Maintain records of processing activities (GDPR Art. 30)",
            "Engage sub-processors only with Client consent and appropriate safeguards"
          ]
        },
        {
          type: "subsection",
          title: "7.4 Data Location and Transfers",
          text: "Data residency and international transfers:"
        },
        {
          type: "list",
          items: [
            "Client-Controlled Location: Candidate Data is stored in Client's designated cloud region (e.g., EU for European clients)",
            "No Unauthorized Transfers: We will not transfer Client Data outside the designated region without consent",
            "Standard Contractual Clauses (SCCs): For EU-US transfers, we use European Commission-approved SCCs",
            "Transfer Impact Assessments: We assist Clients with assessing risks of international data transfers",
            "Sub-processor Locations: List of sub-processors and their locations available in DPA Schedule"
          ]
        },
        {
          type: "subsection",
          title: "7.5 Candidate Rights",
          text: "Candidates whose data is processed through our Platform have rights under GDPR and other laws:"
        },
        {
          type: "list",
          items: [
            "Right to Transparency: Clear information about how their data is used and how AI scoring works",
            "Right to Access: Obtain a copy of their personal data and AI scoring reasoning",
            "Right to Rectification: Correct inaccurate or incomplete information",
            "Right to Erasure: Request deletion of their data (subject to legal retention requirements)",
            "Right to Object: Object to automated decision-making and request human review",
            "Right to Data Portability: Receive their data in a structured, machine-readable format",
            "Right to Lodge Complaint: File complaints with data protection authorities"
          ]
        },
        {
          type: "important",
          text: "Candidate Rights Requests: Candidates should submit rights requests directly to the recruiting organization (Client/data controller). Clients can use Platform tools to facilitate these requests. Rakri AI will assist as a data processor."
        },
        {
          type: "paragraph",
          text: "For complete privacy information, see our Privacy Policy at [LINK]."
        }
      ]
    },
    {
      id: "security",
      title: "8. Security and Data Protection Measures",
      content: [
        {
          type: "paragraph",
          text: "We implement enterprise-grade security to protect Client Data and ensure service integrity."
        },
        {
          type: "subsection",
          title: "8.1 Technical Security Controls"
        },
        {
          type: "list",
          items: [
            "Encryption in Transit: TLS 1.2+ for all data transmitted over networks",
            "Encryption at Rest: AES-256 encryption for data stored in databases and file systems",
            "Access Controls: Role-based access control (RBAC) with principle of least privilege",
            "Authentication: Multi-factor authentication (MFA) for platform access",
            "Network Security: Firewalls, intrusion detection/prevention systems (IDS/IPS), DDoS protection",
            "Application Security: Regular security testing, penetration testing, vulnerability scanning",
            "Audit Logging: Comprehensive logs of all data access and system activities",
            "Data Isolation: Logical separation of each Client's data environment"
          ]
        },
        {
          type: "subsection",
          title: "8.2 Organizational Security Measures"
        },
        {
          type: "list",
          items: [
            "Employee Training: Regular security awareness and data protection training for all staff",
            "Background Checks: Pre-employment screening for employees with data access",
            "Confidentiality Agreements: All employees and contractors sign strict NDAs",
            "Access Management: Regular review and revocation of unnecessary access privileges",
            "Incident Response Plan: Documented procedures for detecting, responding to, and recovering from security incidents",
            "Business Continuity: Disaster recovery and backup systems to ensure service continuity",
            "Vendor Management: Security assessments of all sub-processors and third-party vendors"
          ]
        },
        {
          type: "subsection",
          title: "8.3 Compliance and Certifications",
          text: "We maintain compliance with:"
        },
        {
          type: "list",
          items: [
            "GDPR (EU General Data Protection Regulation)",
            "ISO 27001 (Information Security Management) - [In progress/Planned]",
            "SOC 2 Type II (Service Organization Controls) - [In progress/Planned]",
            "EU-US Data Privacy Framework",
            "Industry best practices (OWASP, NIST, CIS)"
          ]
        },
        {
          type: "subsection",
          title: "8.4 Data Breach Notification",
          text: "In the event of a data breach:"
        },
        {
          type: "list",
          items: [
            "Discovery and Containment: Immediate action to identify and contain the breach",
            "Client Notification: Notify affected Clients within 24 hours of discovery",
            "Authority Notification: Notify supervisory authorities within 72 hours (GDPR Art. 33)",
            "Individual Notification: Assist Clients in notifying affected candidates if required",
            "Breach Report: Provide detailed incident report including nature, scope, and remediation actions",
            "Remediation: Implement corrective measures to prevent future incidents"
          ]
        },
        {
          type: "subsection",
          title: "8.5 Client Security Obligations",
          text: "Clients must:"
        },
        {
          type: "list",
          items: [
            "Maintain security of Authorized User credentials and MFA devices",
            "Implement appropriate security at organizational level (employee training, access policies)",
            "Promptly report security incidents or suspected vulnerabilities to Rakri AI",
            "Ensure secure configuration of Client Infrastructure (cloud environment)",
            "Comply with security requirements specified in MSA and DPA"
          ]
        },
        {
          type: "important",
          text: "Shared Responsibility: Security is a shared responsibility. While we implement robust security for the Platform, Clients are responsible for their infrastructure, user credentials, and organizational security practices."
        }
      ]
    },
    {
      id: "intellectual-property",
      title: "9. Intellectual Property Rights",
      content: [
        {
          type: "subsection",
          title: "9.1 Rakri AI Intellectual Property",
          text: "We retain all rights, title, and interest in:"
        },
        {
          type: "list",
          items: [
            "Platform Software: All code, algorithms, architecture, and functionality of the Platform",
            "AI Models: Machine learning models, training data, algorithms, and methodologies",
            "Documentation: User guides, technical documentation, training materials, and support resources",
            "Trademarks: 'Rakri AI' name, logo, and all related branding",
            "Innovations: Any improvements, enhancements, or derivative works we create",
            "Aggregated Data: Anonymized, aggregated analytics and insights derived from platform usage"
          ]
        },
        {
          type: "important",
          text: "Limited License: These Terms grant you a limited, non-exclusive, non-transferable, revocable license to use the Services solely for your internal business purposes. You do not acquire any ownership rights in our intellectual property."
        },
        {
          type: "subsection",
          title: "9.2 Client Data Ownership",
          text: "You retain all rights, title, and interest in:"
        },
        {
          type: "list",
          items: [
            "Client Data: All candidate resumes, job postings, applications, and content you submit to the Platform",
            "Client Trademarks: Your company name, logo, and branding",
            "Feedback and Configurations: Custom configurations, workflows, and business rules you create",
            "Derivative Data: Reports, analytics, and exports generated from your Client Data"
          ]
        },
        {
          type: "paragraph",
          text: "We do not claim any ownership rights in your Client Data. You grant us a limited license to use Client Data solely to provide the Services, improve AI models (with your consent and only on anonymized data), and comply with legal obligations."
        },
        {
          type: "subsection",
          title: "9.3 Use of Client Data for AI Training",
          text: "AI model improvement:"
        },
        {
          type: "list",
          items: [
            "Opt-In Only: We will NOT use your Client Data to train AI models without your explicit written consent",
            "Anonymization: If you consent to data usage for AI training, data is first irreversibly anonymized and aggregated",
            "No Cross-Client Learning: Your data is never used to improve services for competitors or other clients without anonymization",
            "Transparency: You can review and revoke consent for AI training use at any time",
            "Control: You specify which data categories may be used for training (e.g., anonymized skill keywords, anonymized job descriptions)"
          ]
        },
        {
          type: "subsection",
          title: "9.4 Feedback and Suggestions",
          text: "If you provide feedback, suggestions, or ideas about our Services:"
        },
        {
          type: "list",
          items: [
            "We may freely use feedback to improve our Services without compensation",
            "You waive any intellectual property rights in feedback you provide",
            "We are not obligated to implement any feedback or suggestions",
            "Feedback is considered non-confidential unless covered by a separate NDA"
          ]
        },
        {
          type: "subsection",
          title: "9.5 Third-Party Integrations",
          text: "The Platform may integrate with third-party services (LinkedIn, ATS systems):"
        },
        {
          type: "list",
          items: [
            "Third-party services are subject to their own terms and licenses",
            "We do not guarantee availability or functionality of third-party integrations",
            "Third-party intellectual property remains the property of respective owners",
            "Integration use requires compliance with third-party terms of service"
          ]
        },
        {
          type: "subsection",
          title: "9.6 Copyright Infringement Claims (DMCA)",
          text: "If you believe content on our Services infringes your copyright:"
        },
        {
          type: "list",
          items: [
            "Send written notice to connect@rakriai.com with 'DMCA Notice' in subject",
            "Include: (1) identification of copyrighted work, (2) identification of infringing material, (3) your contact information, (4) statement of good faith belief, (5) statement of accuracy, (6) physical or electronic signature",
            "We will investigate and remove infringing content if appropriate",
            "Repeat infringers may have their accounts terminated"
          ]
        }
      ]
    },
    {
      id: "warranties",
      title: "10. Warranties and Disclaimers",
      content: [
        {
          type: "subsection",
          title: "10.1 Our Warranties",
          text: "We warrant that:"
        },
        {
          type: "list",
          items: [
            "Service Performance: Services will perform materially in accordance with documentation",
            "Authority: We have the legal right and authority to provide the Services",
            "No Harmful Code: Services will not intentionally contain viruses, malware, or harmful code",
            "Compliance: We will comply with applicable data protection laws (GDPR, etc.) in providing Services",
            "Professional Standards: Services will be performed in a professional and workmanlike manner"
          ]
        },
        {
          type: "paragraph",
          text: "Warranty Period: 90 days from service delivery. For warranty breaches, our sole obligation is to re-perform the non-conforming Services or, if we cannot, refund fees paid for the non-conforming Services."
        },
        {
          type: "subsection",
          title: "10.2 Disclaimer of Warranties",
          text: "EXCEPT AS EXPRESSLY STATED ABOVE, SERVICES ARE PROVIDED 'AS IS' AND 'AS AVAILABLE' WITHOUT WARRANTIES OF ANY KIND."
        },
        {
          type: "important",
          text: "TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO:\n\n• IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT\n• WARRANTIES REGARDING ACCURACY, RELIABILITY, OR AVAILABILITY OF SERVICES\n• WARRANTIES THAT SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE\n• WARRANTIES REGARDING AI ACCURACY, CANDIDATE QUALITY, OR HIRING OUTCOMES"
        },
        {
          type: "subsection",
          title: "10.3 AI and Machine Learning Disclaimers",
          text: "Important limitations of AI Services:"
        },
        {
          type: "list",
          items: [
            "No Guarantee of Accuracy: AI scores and recommendations are probabilistic and may contain errors or biases",
            "Human Oversight Required: AI should augment, not replace, human judgment in hiring decisions",
            "Bias Risks: Despite bias mitigation efforts, AI models may reflect biases in training data",
            "Continuous Improvement: AI accuracy improves over time with more data, but perfection is not guaranteed",
            "No Hiring Guarantee: AI scores do not guarantee candidate job performance or cultural fit",
            "Legal Compliance: Client remains responsible for ensuring AI use complies with employment and anti-discrimination laws"
          ]
        },
        {
          type: "important",
          text: "AI Limitations: Our AI Services are designed to assist recruitment professionals, not replace human decision-making. Final hiring decisions should always involve human oversight and judgment. We do not warrant that AI recommendations will lead to successful hires or business outcomes."
        },
        {
          type: "subsection",
          title: "10.4 Third-Party Services Disclaimer",
          text: "For third-party integrations and services:"
        },
        {
          type: "list",
          items: [
            "No Warranty: We do not warrant functionality, availability, or accuracy of third-party services",
            "No Liability: We are not responsible for third-party service failures, data breaches, or terms changes",
            "Client Responsibility: You are responsible for compliance with third-party terms and obtaining necessary licenses",
            "Changes: Third-party integrations may change or be discontinued without notice"
          ]
        },
        {
          type: "subsection",
          title: "10.5 No Legal or HR Advice",
          text: "Our Services do not constitute:"
        },
        {
          type: "list",
          items: [
            "Legal advice regarding employment law, data protection, or regulatory compliance",
            "HR consulting or professional advice regarding hiring practices",
            "Warranty of compliance with specific laws or regulations in your jurisdiction",
            "Substitute for consultation with qualified legal, HR, or compliance professionals"
          ]
        },
        {
          type: "paragraph",
          text: "You should consult with qualified professionals regarding legal compliance, especially for employment law, data protection, and anti-discrimination requirements in your jurisdiction."
        }
      ]
    },
    {
      id: "liability",
      title: "11. Limitation of Liability and Indemnification",
      content: [
        {
          type: "subsection",
          title: "11.1 Limitation of Liability",
          text: "TO THE MAXIMUM EXTENT PERMITTED BY LAW:"
        },
        {
          type: "important",
          text: "EXCLUSION OF CONSEQUENTIAL DAMAGES:\n\nIN NO EVENT SHALL RAKRI AI BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO:\n\n• LOSS OF PROFITS, REVENUE, OR BUSINESS OPPORTUNITIES\n• LOSS OF DATA OR BUSINESS INTERRUPTION\n• COST OF SUBSTITUTE SERVICES OR PROCUREMENT\n• LOSS OF GOODWILL OR REPUTATION\n• HIRING MISTAKES, BAD HIRES, OR RECRUITMENT FAILURES\n• DISCRIMINATION CLAIMS ARISING FROM CLIENT'S USE OF SERVICES\n• REGULATORY FINES OR PENALTIES\n• LEGAL FEES AND LITIGATION COSTS\n\nTHIS EXCLUSION APPLIES EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND REGARDLESS OF THE LEGAL THEORY (CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE)."
        },
        {
          type: "important",
          text: "CAP ON LIABILITY:\n\nOUR TOTAL LIABILITY FOR ALL CLAIMS ARISING FROM OR RELATED TO THESE TERMS OR THE SERVICES SHALL NOT EXCEED THE GREATER OF:\n\n(A) FEES PAID BY CLIENT IN THE 12 MONTHS PRECEDING THE CLAIM, OR\n(B) €10,000\n\nTHIS CAP APPLIES TO ALL CLAIMS COLLECTIVELY, NOT PER INCIDENT."
        },
        {
          type: "subsection",
          title: "11.2 Exceptions to Limitations",
          text: "Liability limitations do not apply to:"
        },
        {
          type: "list",
          items: [
            "Death or Personal Injury: Caused by our negligence",
            "Fraud or Fraudulent Misrepresentation: Intentional deception or fraud",
            "Gross Negligence or Willful Misconduct: Intentional harm or reckless disregard",
            "Indemnification Obligations: Indemnity obligations in Section 11.3",
            "Data Breaches: Liability for data breaches caused by our failure to implement required security measures",
            "Statutory Rights: Rights that cannot be limited by contract under applicable law"
          ]
        },
        {
          type: "subsection",
          title: "11.3 Client Indemnification",
          text: "You agree to indemnify, defend, and hold harmless Rakri AI, its affiliates, officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, costs, and expenses (including reasonable attorneys' fees) arising from:"
        },
        {
          type: "list",
          items: [
            "Your violation of these Terms or applicable laws",
            "Your violation of employment laws, anti-discrimination laws, or data protection laws",
            "Client Data or content you submit to the Platform (including copyright infringement)",
            "Your use of AI Services in violation of applicable law or in a discriminatory manner",
            "Claims by candidates or employees regarding your hiring practices or use of Services",
            "Unauthorized access by your employees or Authorized Users",
            "Your breach of confidentiality or security obligations",
            "Third-party claims arising from your use of the Services"
          ]
        },
        {
          type: "paragraph",
          text: "Indemnification Process: We will notify you promptly of any indemnified claim, allow you to control the defense (with our cooperation), and not settle without your consent (unless settlement unconditionally releases us)."
        },
        {
          type: "subsection",
          title: "11.4 Rakri AI Indemnification",
          text: "We will indemnify you against third-party claims that our Services infringe a third party's intellectual property rights, provided:"
        },
        {
          type: "list",
          items: [
            "You notify us promptly in writing of the claim",
            "You give us sole control of the defense and settlement",
            "You provide reasonable cooperation in the defense",
            "The claim does not arise from your modifications to our Services or combination with third-party services"
          ]
        },
        {
          type: "paragraph",
          text: "Remedies: If Services are found to infringe, we may (at our option): (1) obtain a license for you to continue using Services, (2) modify Services to be non-infringing, or (3) terminate Services and refund prepaid fees for the infringing portion."
        },
        {
          type: "paragraph",
          text: "This Section 11.4 states our sole liability and your exclusive remedy for intellectual property infringement claims."
        },
        {
          type: "subsection",
          title: "11.5 Essential Purpose and Allocation of Risk",
          text: "The liability limitations and disclaimers in these Terms:"
        },
        {
          type: "list",
          items: [
            "Reflect the allocation of risk between the parties",
            "Are essential elements of the bargain between us",
            "Will apply even if limited remedies fail their essential purpose",
            "Are reflected in the pricing of the Services (which would be higher without these limitations)"
          ]
        },
        {
          type: "paragraph",
          text: "Some jurisdictions do not allow exclusion or limitation of certain damages. In such jurisdictions, our liability is limited to the maximum extent permitted by law."
        }
      ]
    },
    {
      id: "termination",
      title: "12. Term, Termination, and Suspension",
      content: [
        {
          type: "subsection",
          title: "12.1 Term",
          text: "These Terms begin when you accept them and continue until terminated as provided below."
        },
        {
          type: "list",
          items: [
            "Website Use: Effective upon each visit; terminates when you stop using the website",
            "Platform Services: Initial term specified in Master Services Agreement (typically 12-36 months)",
            "Renewal: Automatically renews for successive 12-month periods unless either party provides 60 days written notice of non-renewal",
            "Early Termination: Subject to termination provisions below"
          ]
        },
        {
          type: "subsection",
          title: "12.2 Termination for Convenience (Platform Clients)",
          text: "Either party may terminate with notice:"
        },
        {
          type: "list",
          items: [
            "Client Termination: 60 days written notice; no refund of prepaid fees (setup, annual support)",
            "Rakri AI Termination: 90 days written notice; prorated refund of prepaid annual support fees",
            "Usage Charges: All usage charges incurred through termination date are due and payable",
            "Transition Assistance: We will provide reasonable assistance with data export and transition (may be subject to professional services fees)"
          ]
        },
        {
          type: "subsection",
          title: "12.3 Termination for Cause",
          text: "Either party may terminate immediately for cause if the other party:"
        },
        {
          type: "list",
          items: [
            "Materially breaches these Terms and fails to cure within 30 days of written notice",
            "Breaches payment obligations and fails to cure within 10 days of notice",
            "Violates Acceptable Use Policy (immediate termination without notice)",
            "Becomes insolvent, files for bankruptcy, or has a receiver appointed",
            "Ceases business operations or loses required licenses"
          ]
        },
        {
          type: "paragraph",
          text: "No Refund: Termination for cause by Rakri AI results in no refund of prepaid fees. Client remains liable for all outstanding usage charges."
        },
        {
          type: "subsection",
          title: "12.4 Suspension of Services",
          text: "We may suspend Services immediately without notice if:"
        },
        {
          type: "list",
          items: [
            "Account is more than 30 days overdue on payment (after 10-day notice)",
            "We reasonably believe Services are being used for illegal or harmful activities",
            "Client violates Acceptable Use Policy in a manner that threatens security or other clients",
            "Required by law or court order",
            "Necessary to prevent imminent harm or security threat"
          ]
        },
        {
          type: "paragraph",
          text: "Reinstatement: Upon cure of the issue, we will reinstate Services within 24-48 hours. Suspension does not relieve payment obligations."
        },
        {
          type: "subsection",
          title: "12.5 Effects of Termination",
          text: "Upon termination of Platform services:"
        },
        {
          type: "list",
          items: [
            "Access: All Authorized User access to Platform will be terminated",
            "Data Retrieval Period: Client has 30 days to export all Client Data",
            "Data Deletion: After 30-day retrieval period, we will delete all Client Data (or return it per Client instruction)",
            "Backup Retention: Deleted data may remain in backups for up to 90 days, then will be securely destroyed",
            "Confidentiality: Confidentiality obligations survive termination indefinitely",
            "Payment: All outstanding fees become immediately due and payable",
            "Return of Property: Each party will return or destroy the other's confidential information"
          ]
        },
        {
          type: "important",
          text: "Data Export: It is your responsibility to export Client Data before termination or during the 30-day retrieval period. We are not responsible for data loss after this period. Export tools are available in the Platform, or you may request professional data export services (subject to fees)."
        },
        {
          type: "subsection",
          title: "12.6 Survival",
          text: "The following provisions survive termination:"
        },
        {
          type: "list",
          items: [
            "Sections 5 (Payment), 7 (Data Protection - certain obligations), 9 (Intellectual Property), 10 (Disclaimers), 11 (Limitation of Liability), 12.5 (Effects of Termination), 13 (Confidentiality), 15 (Dispute Resolution), and 16 (General Provisions)",
            "Any obligations that by their nature should survive (payment, confidentiality, indemnification, limitation of liability)"
          ]
        }
      ]
    },
    {
      id: "confidentiality",
      title: "13. Confidentiality",
      content: [
        {
          type: "subsection",
          title: "13.1 Definition of Confidential Information",
          text: "'Confidential Information' means non-public information disclosed by one party ('Discloser') to the other party ('Recipient'), including:"
        },
        {
          type: "list",
          items: [
            "Rakri AI Confidential Information: Platform source code, algorithms, AI models, training methodologies, technical architecture, pricing models, business strategies, and customer lists",
            "Client Confidential Information: Client Data, business information, recruitment strategies, and information marked 'Confidential'",
            "Terms of Agreement: Pricing and terms of Master Services Agreement (unless disclosure required by law)"
          ]
        },
        {
          type: "subsection",
          title: "13.2 Obligations",
          text: "Recipient agrees to:"
        },
        {
          type: "list",
          items: [
            "Protect Confidential Information using at least the same degree of care as for its own confidential information (but no less than reasonable care)",
            "Use Confidential Information only for purposes of performing obligations under these Terms",
            "Limit access to employees and contractors with a need to know and who are bound by confidentiality obligations",
            "Not disclose Confidential Information to third parties without Discloser's written consent",
            "Return or destroy Confidential Information upon termination (except as required by law or for archival purposes)"
          ]
        },
        {
          type: "subsection",
          title: "13.3 Exceptions",
          text: "Confidentiality obligations do not apply to information that:"
        },
        {
          type: "list",
          items: [
            "Is or becomes publicly available through no breach by Recipient",
            "Was rightfully known to Recipient before disclosure",
            "Is independently developed by Recipient without use of Confidential Information",
            "Is rightfully received from a third party without confidentiality restrictions",
            "Must be disclosed by law or court order (provided Recipient gives prompt notice to allow Discloser to seek protection)"
          ]
        },
        {
          type: "subsection",
          title: "13.4 Remedies",
          text: "Parties acknowledge that:"
        },
        {
          type: "list",
          items: [
            "Breach of confidentiality may cause irreparable harm for which monetary damages are inadequate",
            "Discloser is entitled to seek injunctive relief and specific performance without proving damages",
            "Such remedies are in addition to other available legal and equitable remedies",
            "Recipient will not oppose injunctive relief on grounds that monetary damages are adequate"
          ]
        }
      ]
    },
    {
      id: "changes",
      title: "14. Changes to Terms and Services",
      content: [
        {
          type: "subsection",
          title: "14.1 Changes to These Terms",
          text: "We may modify these Terms from time to time:"
        },
        {
          type: "list",
          items: [
            "Notice: We will provide at least 30 days notice of material changes via email or prominent website notice",
            "Effective Date: Changes take effect on the date specified in the notice (not earlier than 30 days from notice)",
            "Acceptance: Continued use of Services after effective date constitutes acceptance of modified Terms",
            "Objection: If you object to changes, you may terminate your account before the effective date",
            "Existing Contracts: Material changes do not apply to existing Master Services Agreements until renewal (unless required by law)"
          ]
        },
        {
          type: "subsection",
          title: "14.2 Changes to Services",
          text: "We may modify Services from time to time:"
        },
        {
          type: "list",
          items: [
            "Improvements: We regularly add features, improve performance, and enhance security",
            "Notice: Material changes that negatively affect functionality will be announced at least 30 days in advance",
            "Deprecation: Features may be deprecated with 90 days notice and migration guidance",
            "Security Updates: Security patches may be applied immediately without notice",
            "Third-Party Changes: Third-party integrations may change based on provider requirements"
          ]
        },
        {
          type: "paragraph",
          text: "We strive to minimize disruption from changes and provide advance notice whenever feasible."
        }
      ]
    },
    {
      id: "dispute-resolution",
      title: "15. Dispute Resolution and Governing Law",
      content: [
        {
          type: "subsection",
          title: "15.1 Informal Resolution",
          text: "Before filing any formal claim, parties agree to:"
        },
        {
          type: "list",
          items: [
            "Contact: Send written notice of dispute to connect@rakriai.com (for Rakri AI) or to Client's billing contact (for Client)",
            "Good Faith Negotiation: Engage in good faith negotiations for 30 days to resolve the dispute",
            "Escalation: If not resolved, escalate to senior executives for an additional 30 days of negotiation",
            "Documentation: Maintain records of negotiation attempts for any subsequent proceedings"
          ]
        },
        {
          type: "subsection",
          title: "15.2 Governing Law",
          text: "These Terms are governed by:"
        },
        {
          type: "list",
          items: [
            "EU Clients: Laws of Ireland (for GDPR alignment), excluding conflict of law principles",
            "US Clients: Laws of the State of Delaware, USA, excluding conflict of law principles",
            "Other Clients: As specified in Master Services Agreement, or laws of Ireland by default",
            "International Conventions: UN Convention on Contracts for the International Sale of Goods does NOT apply"
          ]
        },
        {
          type: "subsection",
          title: "15.3 Jurisdiction and Venue",
          text: "Exclusive jurisdiction and venue for disputes:"
        },
        {
          type: "list",
          items: [
            "EU Clients: Courts of Dublin, Ireland (with right to seek enforcement in other jurisdictions)",
            "US Clients: State and federal courts located in Delaware, USA",
            "Other Clients: As specified in Master Services Agreement or courts of Dublin, Ireland by default"
          ]
        },
        {
          type: "paragraph",
          text: "Each party irrevocably waives any objection to venue in the designated courts and consents to personal jurisdiction."
        },
        {
          type: "subsection",
          title: "15.4 Arbitration (Optional for EU Clients)",
          text: "EU clients may opt for binding arbitration:"
        },
        {
          type: "list",
          items: [
            "Arbitration Rules: ICC (International Chamber of Commerce) Rules of Arbitration",
            "Seat of Arbitration: Dublin, Ireland",
            "Language: English",
            "Arbitrators: One arbitrator (claims under €100,000) or three arbitrators (claims over €100,000)",
            "Costs: Each party bears its own costs; arbitrator fees split equally unless arbitrator orders otherwise",
            "Confidentiality: Arbitration proceedings and awards are confidential"
          ]
        },
        {
          type: "subsection",
          title: "15.5 Exceptions to Dispute Resolution",
          text: "Either party may seek court intervention for:"
        },
        {
          type: "list",
          items: [
            "Injunctive Relief: Seeking temporary restraining orders or preliminary injunctions",
            "Intellectual Property Claims: Claims involving intellectual property infringement or trade secret misappropriation",
            "Payment Collection: Collection of undisputed fees",
            "Small Claims: Claims within the jurisdiction of small claims court"
          ]
        },
        {
          type: "subsection",
          title: "15.6 Class Action Waiver",
          text: "TO THE EXTENT PERMITTED BY LAW:"
        },
        {
          type: "important",
          text: "ALL CLAIMS MUST BE BROUGHT IN THE PARTIES' INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, COLLECTIVE, REPRESENTATIVE, OR PRIVATE ATTORNEY GENERAL ACTION.\n\nYOU WAIVE ANY RIGHT TO A JURY TRIAL AND TO PARTICIPATE IN CLASS ACTIONS OR COLLECTIVE ACTIONS."
        },
        {
          type: "paragraph",
          text: "Note: This waiver may not be enforceable in some jurisdictions (e.g., certain EU countries). In such cases, this provision is severed and the remainder of these Terms remain in effect."
        }
      ]
    },
    {
      id: "general",
      title: "16. General Provisions",
      content: [
        {
          type: "subsection",
          title: "16.1 Entire Agreement",
          text: "These Terms, together with the Privacy Policy, DPA, and any Master Services Agreement, constitute the entire agreement between the parties and supersede all prior agreements, understandings, and communications (oral or written) regarding the subject matter. No terms in purchase orders or other Client documents will apply unless expressly agreed in writing by both parties."
        },
        {
          type: "subsection",
          title: "16.2 Amendments",
          text: "No amendment, modification, or waiver of these Terms is effective unless in writing and signed by both parties (except for changes under Section 14.1). Any waiver is effective only in the specific instance and for the specific purpose given."
        },
        {
          type: "subsection",
          title: "16.3 Assignment",
          text: "Assignment and delegation:"
        },
        {
          type: "list",
          items: [
            "Client Assignment: You may not assign or transfer these Terms without our prior written consent (including by merger, acquisition, or operation of law)",
            "Rakri AI Assignment: We may assign these Terms without consent in connection with a merger, acquisition, corporate reorganization, or sale of substantially all assets",
            "Binding Effect: Terms bind and benefit the parties' permitted successors and assigns",
            "Attempted Invalid Assignment: Any attempted assignment in violation of this provision is void"
          ]
        },
        {
          type: "subsection",
          title: "16.4 Force Majeure",
          text: "Neither party is liable for failure to perform due to causes beyond reasonable control, including:"
        },
        {
          type: "list",
          items: [
            "Natural disasters (earthquakes, floods, fires, storms)",
            "War, terrorism, civil unrest, or government actions",
            "Pandemics or public health emergencies",
            "Internet or telecommunications failures (not caused by the party claiming force majeure)",
            "Third-party service provider failures (cloud infrastructure, power)",
            "Labor disputes or strikes not involving the party's own employees"
          ]
        },
        {
          type: "paragraph",
          text: "Obligations: Party claiming force majeure must (1) promptly notify the other party, (2) use reasonable efforts to mitigate impact, (3) resume performance as soon as practicable. If force majeure continues for more than 60 days, either party may terminate the affected Services upon written notice."
        },
        {
          type: "important",
          text: "Payment Obligations: Force majeure does not excuse Client's payment obligations for Services already provided or for Services not affected by the force majeure event."
        },
        {
          type: "subsection",
          title: "16.5 Independent Contractors",
          text: "Parties are independent contractors. These Terms do not create any:"
        },
        {
          type: "list",
          items: [
            "Partnership, joint venture, or agency relationship",
            "Employment relationship (no employees, no benefits)",
            "Franchise or distribution relationship",
            "Authority to bind the other party or make commitments on their behalf",
            "Fiduciary duties beyond those explicitly stated in these Terms"
          ]
        },
        {
          type: "subsection",
          title: "16.6 Severability",
          text: "If any provision of these Terms is held invalid, illegal, or unenforceable:"
        },
        {
          type: "list",
          items: [
            "Severance: The invalid provision is severed from these Terms",
            "Reformation: Courts are authorized to reform the provision to the minimum extent necessary to make it enforceable",
            "Remaining Terms: The remaining provisions continue in full force and effect",
            "Essential Provisions: If severance substantially impairs the value of the agreement, either party may terminate"
          ]
        },
        {
          type: "subsection",
          title: "16.7 No Third-Party Beneficiaries",
          text: "These Terms are solely for the benefit of the parties and their successors and permitted assigns. No third party (including candidates, employees, contractors, or other service users) has any rights under these Terms unless explicitly granted."
        },
        {
          type: "subsection",
          title: "16.8 Notices",
          text: "All legal notices must be:"
        },
        {
          type: "list",
          items: [
            "Format: In writing and in English",
            "To Rakri AI: Email to connect@rakriai.com (marked 'Legal Notice') or postal mail to address specified in Master Services Agreement",
            "To Client: Email to billing contact or administrator email on file, or postal mail to address in account",
            "Effective Date: Notices effective upon receipt (email) or 3 business days after mailing (postal mail)",
            "Change of Address: Parties must promptly notify of any change in contact information"
          ]
        },
        {
          type: "subsection",
          title: "16.9 Export Control and Sanctions Compliance",
          text: "Clients agree to comply with all applicable export control and sanctions laws:"
        },
        {
          type: "list",
          items: [
            "US Export Controls: Export Administration Regulations (EAR), International Traffic in Arms Regulations (ITAR) if applicable",
            "EU Export Controls: EU Dual-Use Regulation and member state export laws",
            "Sanctions: US OFAC sanctions, EU sanctions, UN sanctions",
            "Prohibited Use: Services may not be used by or for sanctioned individuals, entities, or countries",
            "Certification: Client certifies it is not on any sanctions or denied parties list"
          ]
        },
        {
          type: "subsection",
          title: "16.10 Government Clients",
          text: "If Client is a government entity:"
        },
        {
          type: "list",
          items: [
            "US Government: Services are 'Commercial Items' as defined in FAR 2.101, provided with only those rights customarily provided to the public",
            "EU Government: Services are provided under standard commercial terms; modifications for public procurement compliance may be negotiated",
            "Special Terms: Government-specific terms (FAR clauses, security requirements) must be agreed in a separate addendum"
          ]
        },
        {
          type: "subsection",
          title: "16.11 Language",
          text: "These Terms are drafted in English. Any translations are provided for convenience only. In case of conflict between English and translated versions, the English version controls."
        },
        {
          type: "subsection",
          title: "16.12 Headings and Interpretation",
          text: "Section headings are for convenience only and do not affect interpretation. Use of 'including' means 'including but not limited to.' 'Or' is inclusive (and/or). References to 'days' mean calendar days unless specified as 'business days.'"
        }
      ]
    },
    {
      id: "contact-info",
      title: "17. Contact Information",
      content: [
        {
          type: "paragraph",
          text: "For questions, concerns, or notices regarding these Terms of Service:"
        },
        {
          type: "contact-info",
          items: [
            { label: "Company Name", value: "Rakri AI" },
            { label: "General Inquiries", value: "connect@rakriai.com" },
            { label: "Support", value: "connect@rakriai.com" },
            { label: "Legal Notices", value: "connect@rakriai.com (Subject: Legal Notice)" },
            { label: "Business Hours", value: "Monday - Friday, 9:00 AM - 6:00 PM CET" }
          ]
        },
        {
          type: "paragraph",
          text: "We strive to respond to all inquiries within 48 hours (business days)."
        },
        {
          type: "important",
          text: "Effective Date: These Terms are effective as of January 17, 2025. By using our Services after this date, you agree to be bound by these Terms."
        },
        {
          type: "paragraph",
          text: "Thank you for choosing Rakri AI. We are committed to providing you with powerful, compliant, and transparent AI-powered recruitment solutions."
        }
      ]
    }
  ]
};

export default termsOfServiceContent;
